/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import javax.swing.JOptionPane;
/**
 *
 * @author migue
 */
public class JCadastrarConfiguracoes extends javax.swing.JFrame {

    /**
     * Creates new form JCadastrarCategoria
     */
    public JCadastrarConfiguracoes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTextfilo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextraizes = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextfolhas = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextespinhos = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextclima = new javax.swing.JTextField();
        retornomenuconf = new javax.swing.JButton();
        cadastrarconf = new javax.swing.JButton();
        Limparconf = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Bogart Trial Black", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 51));
        jLabel2.setText("Cadastrar Configurações");

        jTextfilo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextfiloActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Bogart Trial", 0, 14)); // NOI18N
        jLabel4.setText("Filo:");

        jTextraizes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextraizesActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Bogart Trial", 0, 14)); // NOI18N
        jLabel5.setText("Raízes:");

        jTextfolhas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextfolhasActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Bogart Trial", 0, 14)); // NOI18N
        jLabel6.setText("Folhas:");

        jLabel7.setFont(new java.awt.Font("Bogart Trial", 0, 14)); // NOI18N
        jLabel7.setText("Espinhos:");

        jTextespinhos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextespinhosActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Bogart Trial", 0, 14)); // NOI18N
        jLabel8.setText("Clima:");

        jTextclima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextclimaActionPerformed(evt);
            }
        });

        retornomenuconf.setFont(new java.awt.Font("Bogart Trial", 1, 14)); // NOI18N
        retornomenuconf.setText("Retornar ao \nmenu...");
        retornomenuconf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retornomenuconfActionPerformed(evt);
            }
        });

        cadastrarconf.setFont(new java.awt.Font("Bogart Trial", 1, 14)); // NOI18N
        cadastrarconf.setText("Cadastrar");
        cadastrarconf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarconfActionPerformed(evt);
            }
        });

        Limparconf.setFont(new java.awt.Font("Bogart Trial", 1, 14)); // NOI18N
        Limparconf.setText("Limpar");
        Limparconf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimparconfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cadastrarconf, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Limparconf, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(retornomenuconf)
                        .addGap(93, 93, 93))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextraizes, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextfilo, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextfolhas, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextespinhos, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextclima, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextfilo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextraizes, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextfolhas, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextespinhos, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextclima, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Limparconf, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cadastrarconf))
                .addGap(18, 18, 18)
                .addComponent(retornomenuconf, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextfiloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextfiloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextfiloActionPerformed

    private void jTextraizesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextraizesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextraizesActionPerformed

    private void jTextfolhasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextfolhasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextfolhasActionPerformed

    private void jTextespinhosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextespinhosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextespinhosActionPerformed

    private void jTextclimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextclimaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextclimaActionPerformed

    private void retornomenuconfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retornomenuconfActionPerformed
        this.dispose();
        JMenu jmenu = new JMenu();
        jmenu.setVisible(true);
    }//GEN-LAST:event_retornomenuconfActionPerformed

    private void cadastrarconfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarconfActionPerformed
        JOptionPane.showMessageDialog(null,"Dados Cadastrados com Sucesso!");
    }//GEN-LAST:event_cadastrarconfActionPerformed

    private void LimparconfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimparconfActionPerformed
        jTextfilo.setText("");
        jTextraizes.setText("");
        jTextfolhas.setText("");
        jTextespinhos.setText("");
        jTextclima.setText("");
    }//GEN-LAST:event_LimparconfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JCadastrarConfiguracoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JCadastrarConfiguracoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JCadastrarConfiguracoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JCadastrarConfiguracoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JCadastrarConfiguracoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Limparconf;
    private javax.swing.JButton cadastrarconf;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextclima;
    private javax.swing.JTextField jTextespinhos;
    private javax.swing.JTextField jTextfilo;
    private javax.swing.JTextField jTextfolhas;
    private javax.swing.JTextField jTextraizes;
    private javax.swing.JButton retornomenuconf;
    // End of variables declaration//GEN-END:variables
}
