/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora;

/**
 *
 * @author migue
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button3 = new java.awt.Button();
        button9 = new java.awt.Button();
        button6 = new java.awt.Button();
        button8 = new java.awt.Button();
        button5 = new java.awt.Button();
        button7 = new java.awt.Button();
        button4 = new java.awt.Button();
        buttonsoma = new java.awt.Button();
        button2 = new java.awt.Button();
        buttonresult = new java.awt.Button();
        buttonmenos = new java.awt.Button();
        jTextField1 = new javax.swing.JTextField();
        button1 = new java.awt.Button();
        button0 = new java.awt.Button();
        buttonvirg = new java.awt.Button();
        jTextFieldresult = new javax.swing.JTextField();
        buttonmult = new java.awt.Button();
        buttondiv = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 153));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));

        button3.setBackground(new java.awt.Color(255, 255, 102));
        button3.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        button3.setLabel("3");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });

        button9.setBackground(new java.awt.Color(255, 255, 102));
        button9.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        button9.setLabel("9");
        button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button9ActionPerformed(evt);
            }
        });

        button6.setBackground(new java.awt.Color(255, 255, 102));
        button6.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        button6.setLabel("6");
        button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button6ActionPerformed(evt);
            }
        });

        button8.setBackground(new java.awt.Color(255, 255, 102));
        button8.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        button8.setLabel("8");
        button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button8ActionPerformed(evt);
            }
        });

        button5.setBackground(new java.awt.Color(255, 255, 102));
        button5.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        button5.setLabel("5");
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });

        button7.setBackground(new java.awt.Color(255, 255, 102));
        button7.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        button7.setLabel("7");
        button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button7ActionPerformed(evt);
            }
        });

        button4.setBackground(new java.awt.Color(255, 255, 102));
        button4.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        button4.setLabel("4");
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });

        buttonsoma.setBackground(new java.awt.Color(255, 255, 102));
        buttonsoma.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        buttonsoma.setLabel("+");
        buttonsoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonsomaActionPerformed(evt);
            }
        });

        button2.setBackground(new java.awt.Color(255, 255, 102));
        button2.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        button2.setLabel("2");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        buttonresult.setBackground(new java.awt.Color(255, 255, 102));
        buttonresult.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        buttonresult.setLabel("=");
        buttonresult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonresultActionPerformed(evt);
            }
        });

        buttonmenos.setBackground(new java.awt.Color(255, 255, 102));
        buttonmenos.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        buttonmenos.setLabel("-");
        buttonmenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonmenosActionPerformed(evt);
            }
        });

        jTextField1.setBackground(new java.awt.Color(255, 255, 153));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        button1.setBackground(new java.awt.Color(255, 255, 102));
        button1.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        button1.setLabel("1");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        button0.setBackground(new java.awt.Color(255, 255, 102));
        button0.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        button0.setLabel("0");
        button0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button0ActionPerformed(evt);
            }
        });

        buttonvirg.setActionCommand(".");
        buttonvirg.setBackground(new java.awt.Color(255, 255, 102));
        buttonvirg.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        buttonvirg.setLabel(".");
        buttonvirg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonvirgActionPerformed(evt);
            }
        });

        jTextFieldresult.setBackground(new java.awt.Color(255, 255, 153));
        jTextFieldresult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldresultActionPerformed(evt);
            }
        });

        buttonmult.setActionCommand("x");
        buttonmult.setBackground(new java.awt.Color(255, 255, 102));
        buttonmult.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        buttonmult.setLabel("x");
        buttonmult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonmultActionPerformed(evt);
            }
        });

        buttondiv.setActionCommand("÷");
        buttondiv.setBackground(new java.awt.Color(255, 255, 102));
        buttondiv.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        buttondiv.setLabel("÷");
        buttondiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttondivActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(button4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(2, 2, 2)
                                    .addComponent(button5, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(2, 2, 2)
                                    .addComponent(button6, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(2, 2, 2)
                                    .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(2, 2, 2)
                                    .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(button7, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(button8, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(button0, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(buttonvirg, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(button9, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(buttonsoma, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttonmenos, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(buttondiv, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttonmult, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(buttonresult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jTextFieldresult)
                    .addComponent(jTextField1))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(242, 242, 242)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jTextFieldresult, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonsoma, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonmult, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button6, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button5, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonmenos, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttondiv, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(button7, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button9, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button8, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(button0, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonvirg, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(buttonresult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonresultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonresultActionPerformed
        jTextFieldresult.setText("Resultado: "+String.valueOf(num));
    }//GEN-LAST:event_buttonresultActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        String numero;
        numero = jTextField1.getText();
        //jTextField1.setText("");
        jTextField1.setText(numero + "1");        
    }//GEN-LAST:event_button1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
       String numero;
        numero = jTextField1.getText();
        jTextField1.setText(numero + "2");
    }//GEN-LAST:event_button2ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        String numero;
        numero = jTextField1.getText();
        jTextField1.setText(numero + "3");
    }//GEN-LAST:event_button3ActionPerformed

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        String numero;
        numero = jTextField1.getText();
        jTextField1.setText(numero + "4");
    }//GEN-LAST:event_button4ActionPerformed

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
       String numero;
        numero = jTextField1.getText();
        jTextField1.setText(numero + "5");
    }//GEN-LAST:event_button5ActionPerformed

    private void button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button6ActionPerformed
        String numero;
        numero = jTextField1.getText();
        jTextField1.setText(numero + "6");
    }//GEN-LAST:event_button6ActionPerformed

    private void button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button7ActionPerformed
       String numero;
        numero = jTextField1.getText();
        jTextField1.setText(numero + "7");
    }//GEN-LAST:event_button7ActionPerformed

    private void button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button8ActionPerformed
       String numero;
        numero = jTextField1.getText();
        jTextField1.setText(numero + "8");
    }//GEN-LAST:event_button8ActionPerformed

    private void button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button9ActionPerformed
        String numero;
        numero = jTextField1.getText();
        jTextField1.setText(numero + "9");
    }//GEN-LAST:event_button9ActionPerformed

    private void button0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button0ActionPerformed
        String numero;
        numero = jTextField1.getText();
        jTextField1.setText(numero + "0");
    }//GEN-LAST:event_button0ActionPerformed

    private void buttonvirgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonvirgActionPerformed
       String numero;
        numero = jTextField1.getText();
        jTextField1.setText(numero + ".");
    }//GEN-LAST:event_buttonvirgActionPerformed
        double num=0;
        int cont=0;
   
    private void buttonsomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonsomaActionPerformed
      //jTextField1.setText("");
      double num1;
      if(cont==0){
        num1 = Double.parseDouble(jTextField1.getText());
       jTextField1.setText("");
       num = num1;
      // jTextField1.setText(String.valueOf(num));
       // jTextField1.setText("");
       cont++;
      }
      else{
         // jTextField1.setText("");
        num1 = Double.parseDouble(jTextField1.getText());
       jTextField1.setText("");
       num += num1;
        jTextFieldresult.setText("Resultado: "+String.valueOf(num));
       // jTextField1.setText("");
         System.out.print(num+""+num1);
      }
      
      
       //
      
       
    }//GEN-LAST:event_buttonsomaActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextFieldresultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldresultActionPerformed
       
        
    }//GEN-LAST:event_jTextFieldresultActionPerformed

    private void buttonmenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonmenosActionPerformed
        double num1;
      if(cont==0){
        num1 = Double.parseDouble(jTextField1.getText());
       jTextField1.setText("");
       num = num1;
      // jTextField1.setText(String.valueOf(num));
       // jTextField1.setText("");
       cont++;
      }
      else{
         // jTextField1.setText("");
        num1 = Double.parseDouble(jTextField1.getText());
       jTextField1.setText("");
       num -= num1;
        jTextFieldresult.setText("Resultado: "+String.valueOf(num));
       // jTextField1.setText("");
         System.out.print(num+""+num1);
      }
    }//GEN-LAST:event_buttonmenosActionPerformed
    private void buttonmultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonmultActionPerformed
       double num1;
      if(cont==0){
        num1 = Double.parseDouble(jTextField1.getText());
       jTextField1.setText("");
       num = num1;
      // jTextField1.setText(String.valueOf(num));
       // jTextField1.setText("");
       cont++;
      }
      else{
         // jTextField1.setText("");
        num1 = Double.parseDouble(jTextField1.getText());
       jTextField1.setText("");
       num *= num1;
        jTextFieldresult.setText("Resultado: "+String.valueOf(num));
       // jTextField1.setText("");
         System.out.print(num+""+num1);
      }
    }//GEN-LAST:event_buttonmultActionPerformed
    int cont3;
    private void buttondivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttondivActionPerformed
         double num1;
      if(cont3==0){
        num1 = Double.parseDouble(jTextField1.getText());
       jTextField1.setText("");
       num = num1;
      // jTextField1.setText(String.valueOf(num));
       // jTextField1.setText("");
       cont3++;
      }
      else{
         // jTextField1.setText("");
        num1 = Double.parseDouble(jTextField1.getText());
       jTextField1.setText("");
       num /= num1;
        jTextFieldresult.setText("Resultado: "+String.valueOf(num));
       // jTextField1.setText("");
         System.out.print(num+""+num1);
      }
    }//GEN-LAST:event_buttondivActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button0;
    private java.awt.Button button1;
    private java.awt.Button button2;
    private java.awt.Button button3;
    private java.awt.Button button4;
    private java.awt.Button button5;
    private java.awt.Button button6;
    private java.awt.Button button7;
    private java.awt.Button button8;
    private java.awt.Button button9;
    private java.awt.Button buttondiv;
    private java.awt.Button buttonmenos;
    private java.awt.Button buttonmult;
    private java.awt.Button buttonresult;
    private java.awt.Button buttonsoma;
    private java.awt.Button buttonvirg;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldresult;
    // End of variables declaration//GEN-END:variables
}
